# Homework 00: Python Basics
### Ana Belen Barcenas J. 

This is meant as a Python refresher (or crash course).

**1**. (25 points) 

The code below generates the unique Pythagorean triplets $(a, b, c)$ where $a^2 + b^2 = c^2$ using a nested list comprehension for values of $a, b, c \le 20$.

```Python
triplets = [(a, b, c) for a in range(1, 21) for b in range(a, 21) for c in range(b, 21) if a**2 + b**2 == c**2]
```

- Rewrite using a for loop with the same functionality

In [13]:
triplets = [(a, b, c) for a in range(1, 21) for b in range(a, 21) for c in range(b, 21) if a**2 + b**2 == c**2]
triplets

[(3, 4, 5), (5, 12, 13), (6, 8, 10), (8, 15, 17), (9, 12, 15), (12, 16, 20)]

In [2]:
import math

triplets = []
for b in range(1, 21):
    for a in range(1, b):
        c = math.sqrt( a * a + b * b)
        if c % 1 == 0:
            tup = (a, b, int(c))
            triplets.append(tup)
            
print(triplets)


[(3, 4, 5), (6, 8, 10), (5, 12, 13), (9, 12, 15), (8, 15, 17), (12, 16, 20), (15, 20, 25)]


**2**. (25 points) 

The code below generates the sum of numbers meeting some predicate condition.

```python
def pred(a):
    if a % 3 == 0:
        return True
    else:
        return False
    
s = []
for i in range(100):
    if pred(i):
        s.append(i**2)

sum(s)
```

- Rewrite using `map`, `filter`, `reduce` and a `lambda` functions to achieve the same functionality.  Do not use the `pred` or `sum` functions.

In [5]:
def pred(a):
    if a % 3 == 0:
        return True
    else:
        return False
    
s = []
for i in range(7):
    if pred(i):
        s.append(i**2)

sum(s)

45

In [33]:
from functools import reduce

In [8]:
number_list = range(100)
divisible_three = list(filter(lambda x: x % 3 == 0, number_list))
print(divisible_three)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [48]:
squared = list(map(lambda x: x**2, divisible_three))
print(squared)

[0, 9, 36, 81, 144, 225, 324, 441, 576, 729, 900, 1089, 1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356, 4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801]


In [50]:
reduce((lambda x, y: x + y), squared)

112761

All together:

In [52]:
reduce((lambda x, y: x + y), list(map(lambda x: x**2, list(filter(lambda x: x % 3 == 0, number_list)))))

112761

**3**. (50 points)

- Perform the median polish to calculate just the *residuals* for this [example](https://mgimond.github.io/ES218/Week11a.html) in Python. 
- Use the matrix `xs` provided
- Display the final result after 3 iterations to 1 decimal place and check if it agrees with 

![img](https://mgimond.github.io/ES218/img/twoway_09.jpg)

In [9]:
import numpy as np

In [24]:
xs = np.array([
    (25.3,32.1,38.8,25.4), 
    (25.3,29,31,21.1),
    (18.2,18.8,19.3,20.3),
    (18.3,24.3,15.7,24),
    (16.3,19,16.8,17.5)
]).T

In [25]:
xs

array([[25.3, 25.3, 18.2, 18.3, 16.3],
       [32.1, 29. , 18.8, 24.3, 19. ],
       [38.8, 31. , 19.3, 15.7, 16.8],
       [25.4, 21.1, 20.3, 24. , 17.5]])

In [26]:
for i in [1,2,3]:
    med_overall = (np.median(xs))
    xs = xs - med_overall
    
    med_row = np.median(xs, axis=1) #row
    xs = (xs.transpose() - med_row).transpose()
    med_col = np.median(xs, axis=0) #col
    xs = (xs - med_col)
print("Residuals after 3 iterations: \n")
print(np.round(xs,1))

Residuals after 3 iterations: 

[[-1.4  0.2  0.  -1.   0.7]
 [ 1.4 -0.2 -3.4  1.  -0.7]
 [11.   4.7 -0.  -4.7  0. ]
 [-3.1 -5.9  0.3  2.9  0. ]]


In [19]:
med_overall = (np.median(xs))
xs = xs - med_overall
    
med_row = np.median(xs, axis=1) #row
xs = (xs.transpose() - med_row).transpose()
med_col = np.median(xs, axis=0) #col
xs = (xs - med_col)

np.round(xs,1)

array([[-0.4,  1.2,  0.3,  0. ,  1.1],
       [ 0.4, -1.2, -5. ,  0. , -2.2],
       [12.1,  5.8,  0.5, -3.6,  0.6],
       [-3.1, -5.8, -0.3,  2.9, -0.6]])

In [20]:
med_overall = (np.median(xs))
xs = xs - med_overall

med_row = np.median(xs, axis=1) #row
xs = (xs.transpose() - med_row).transpose()
med_col = np.median(xs, axis=0) #col
xs = (xs - med_col)

np.round(xs,1)

array([[-1.2,  0.4,  0. , -0.8,  0.7],
       [ 1.2, -0.4, -3.8,  0.8, -1.1],
       [11.1,  4.9, -0. , -4.6,  0. ],
       [-3. , -5.7,  0.3,  3. ,  0. ]])

In [21]:
med_overall = (np.median(xs))
xs = xs - med_overall

med_row = np.median(xs, axis=1) #row
xs = (xs.transpose() - med_row).transpose()
med_col = np.median(xs, axis=0) #col
xs = (xs - med_col)

np.round(xs,1)

array([[-1.4,  0.2,  0. , -1. ,  0.7],
       [ 1.4, -0.2, -3.4,  1. , -0.7],
       [11. ,  4.7, -0. , -4.7,  0. ],
       [-3.1, -5.9,  0.3,  2.9,  0. ]])